name: Build and Publish chartscan Binaries

on:
  release:
    types: [created]  # Trigger the workflow only when a new release is created

jobs:
  build:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        go-version: [1.22]
        architecture: [amd64, arm64, 386]
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Set up Go ${{ matrix.go-version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}
          
      - name: Cache Go Modules
        uses: actions/cache@v4
        with:
          path: ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-${{ hashFiles('**/go.mod') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-
      
      - name: Install Go Dependencies
        run: go mod tidy
        
      - name: Build chartscan Binary
        run: |
          GOARCH=${{ matrix.architecture }} GOOS=linux go build cmd/chartscan/main.go -o chartscan-${{ matrix.architecture }} .
        
      - name: Upload Binaries as Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chartscan-binaries-${{ matrix.architecture }}
          path: chartscan-${{ matrix.architecture }}
          
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            chartscan-amd64
            chartscan-arm64
            chartscan-386
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
